source "http://rubygems.org"

gem "rails", "5.2.4.6"
gem "haml-rails", ">= 0.5.3"
gem "jquery-rails", ">= 4.0.1"
gem "pg"
gem "simple_form", ">= 4.0.0"

group :development, :test do
  gem "rspec", "2.7"
  gem "rspec-rails", "2.8.0"
  gem "rspec-core", "2.7"
  gem "rspec-expectations", "2.7"
  gem "rspec-mocks", "2.7"
  gem "database_cleaner"
  gem "fabrication"
  gem "capybara", ">= 1.1.2"
  gem "spork"
end
