source 'https://rubygems.org'

gem 'rails', '4.0.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', '~> 4.0.0'
  gem 'coffee-rails', '~> 4.0.0'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails', '>= 2.0.2'

group :development, :test do
  gem 'rspec-rails', '>= 2.10.1'
  gem 'capybara'
  gem 'ffaker'
  gem 'shoulda-matchers'
  gem 'fabrication'
  gem 'awesome_print'
end
